CREATE TABLE `feed` (
  `id` INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  `data_inclusao` DATETIME NOT NULL,
  `texto` VARCHAR(255) NOT NULL,
  `link_img` VARCHAR(255) NOT NULL,
  `link` VARCHAR(255)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;


CREATE TABLE `evento` (
  `id` INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  `data_inclusao` DATETIME NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `inicio_inscricao` DATE NOT NULL,
  `fim_inscricao` DATE NOT NULL,
  `link` VARCHAR(255) NOT NULL,
  `vagas` INT NOT NULL
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
